spellername = "Liv"
spellerversion = "0.1.1"

# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Liv spellchecker"
liv = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Liv, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
liv = "TRANSLATE: A spellchecker for Liv, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.liv"

[windows]
system_product_code = "{A3F9B2C0-1D7D-4223-930E-005B22762066}_is1"
legacy_product_codes = [
    { value = "73BF1A03-DFB6-4431-BB4F-6609476CCB7A", kind = "nsis" },
    { value = "C00BB1E5-4632-40B5-BAA9-9D1851DAA035", kind = "nsis" }
]
