template = "https://github.com/giellalt/template-lang-und"
rev_id = 322
template_sha = "eb14866dc080346b46def6f27a66b1b5eca59898"

[replacements]
__GLOTTOLOG_ID__ = "livv1244"
__REPO__ = "lang-liv"
__UND2C__ = "liv"
__UNDEFINED__ = "Liv"
__UND__ = "liv"
