[package]
name = "liv"
human_name = "Liv"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.liv]
filename = "liv-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-liv"
platform = "windows"
uuid = "73BF1A03-DFB6-4431-BB4F-6609476CCB7A"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.liv"
package = "speller-liv"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-liv-mso"
platform = "windows"
uuid = "C00BB1E5-4632-40B5-BAA9-9D1851DAA035"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-liv"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
